using System;
using MigraDoc.DocumentObjectModel;

namespace TPS_Validation.Internal
{
	internal class HeaderAndFooter
	{
		public void Add(Section section)
		{
			AddHeader(section);
			AddFooter(section);
		}

		private void AddHeader(Section section)
		{
			var header = section.Headers.Primary.AddParagraph();
			header.Style = StyleNames.Header;
			header.Format.AddTabStop(Size.GetWidth(section), TabAlignment.Right);

			header.AddText($"TPS Validation and QA");
			header.AddTab();
			header.AddText($"Machine ID: will go here");
		}

		private void AddFooter(Section section)
		{
			var footer = section.Footers.Primary.AddParagraph();
			footer.Style = StyleNames.Footer;
			footer.Format.AddTabStop(Size.GetWidth(section), TabAlignment.Right);

			footer.AddText($"Generated by user.Username at {DateTime.Now:g}");
			footer.AddTab();
			footer.AddText("Page ");
			footer.AddPageField();
			footer.AddText(" of ");
			footer.AddNumPagesField();
		}
	}
}